#!/usr/bin/env bash
# Facilitates the relocation of a file from Holberton's client to another destination.
# Requires four parameters:
#       The directory path of the file intended for transfer.
#       The IP address of the server where the file will be transferred.
#       The username utilized for establishing the scp connection.
#       The file path to the SSH private key used by scp for authentication.


if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
