#!/usr/bin/env bash

# Configures Nginx server to redirect /redirect_me to another page with a "301 Moved Permanently"

# Define the redirection configuration
REDIRECT_CONFIG="location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

# Add the redirection configuration to the Nginx default site configuration file
echo "$REDIRECT_CONFIG" | tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx without using systemctl
service nginx restart > /dev/null 2>&1 || /etc/init.d/nginx restart > /dev/null 2>&1
