#!/usr/bin/env bash
# Sets up a new 404 error page

# Update package repositories
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx 

# Create a custom 404 page with the required string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure nginx to use the custom 404 page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF'

# Restart nginx service to apply changes
sudo service nginx restart
