#!/usr/bin/env bash

# Configures Nginx server to have a custom 404 page that contains the string "Ceci n'est pas une page"

# Define the custom 404 page configuration
NOT_FOUND_CONFIG="error_page 404 /404_custom_page;
location = /404_custom_page {
    internal;
    echo 'Ceci n'est pas une page';
}"

# Add the custom 404 page configuration to the Nginx default site configuration file
echo "$NOT_FOUND_CONFIG" | tee -a /etc/nginx/sites-available/default > /dev/null

# Restart Nginx without using systemctl
service nginx restart > /dev/null 2>&1 || /etc/init.d/nginx restart > /dev/null 2>&1
